package dev.arc.engine.expression;

import java.util.*;

/** Editor group names for Excel functions without a curated help override. */
final class ExcelFunctionCategories {
  private static final Map<String, String> CATEGORIES = create();

  static String category(String name) {
    return CATEGORIES.getOrDefault(name, "Workbook & other");
  }

  private static Map<String, String> create() {
    var groups = new LinkedHashMap<String, String>();
    groups.put(
        "Math",
        "CEILING CEILING.MATH CEILING.PRECISE COMBIN EVEN EXP FACT FACTDOUBLE FLOOR.MATH"
            + " FLOOR.PRECISE GCD INT LCM LN LOG LOG10 MOD MROUND MULTINOMIAL ODD PI POWER PRODUCT"
            + " QUOTIENT ROMAN SERIESSUM SIGN SQRT SQRTPI SUBTOTAL SUMIFS SUMSQ SUMX2MY2 SUMX2PY2"
            + " SUMXMY2 TRUNC");
    groups.put(
        "Trigonometry",
        "ACOS ACOSH ASIN ASINH ATAN ATAN2 ATANH COS COSH DEGREES RADIANS SIN SINH TAN TANH");
    groups.put(
        "Statistics",
        "AVEDEV AVERAGEA AVERAGEIF AVERAGEIFS CORREL COVAR COVARIANCE.P COVARIANCE.S DEVSQ FISHER"
            + " FISHERINV FORECAST FORECAST.LINEAR FREQUENCY GROWTH HARMEAN INTERCEPT KURT LARGE"
            + " LINEST LOGEST MAXA MAXIFS MINA MINIFS MODE PEARSON PERCENTILE PERCENTRANK"
            + " PERCENTRANK.EXC PERCENTRANK.INC PERMUT QUARTILE RANK RSQ SKEW SLOPE SMALL"
            + " STANDARDIZE STDEV.P STDEV.S STDEVA STDEVPA STEYX TREND TRIMMEAN VAR.P VAR.S VARA"
            + " VARPA");
    groups.put(
        "Probability",
        "BETADIST BETAINV BINOMDIST CHIDIST CHIINV CHITEST CONFIDENCE CRITBINOM EXPONDIST FDIST"
            + " FINV FTEST GAMMADIST GAMMAINV GAMMALN HYPGEOMDIST LOGINV LOGNORMDIST NEGBINOMDIST"
            + " NORM.DIST NORM.INV NORM.S.DIST NORM.S.INV NORMDIST NORMINV NORMSDIST NORMSINV"
            + " POISSON POISSON.DIST PROB T.DIST T.DIST.2T T.DIST.RT TDIST TINV TTEST WEIBULL"
            + " ZTEST");
    groups.put(
        "Text",
        "ASC BAHTTEXT CHAR CODE CONCATENATE DBCS DOLLAR EXACT FINDB FIXED JIS LEFTB LENB MIDB"
            + " NUMBERSTRING NUMBERVALUE PHONETIC REPLACE REPLACEB RIGHTB SEARCHB T TEXTJOIN"
            + " USDOLLAR VALUE");
    groups.put(
        "Date & time",
        "DATEDIF DATESTRING DATEVALUE DAYS DAYS360 EDATE EOMONTH HOUR MINUTE NETWORKDAYS SECOND"
            + " TIME TIMEVALUE WEEKNUM WORKDAY WORKDAY.INTL YEARFRAC NOW TODAY");
    groups.put(
        "Finance",
        "ACCRINT ACCRINTM AMORDEGRC AMORLINC COUPDAYBS COUPDAYS COUPDAYSNC COUPNCD COUPNUM COUPPCD"
            + " CUMIPMT CUMPRINC DB DDB DISC DOLLARDE DOLLARFR DURATION EFFECT FV FVSCHEDULE"
            + " INTRATE IPMT IRR ISPMT MDURATION MIRR NOMINAL NPER ODDFPRICE ODDFYIELD ODDLPRICE"
            + " ODDLYIELD PPMT PRICE PRICEDISC PRICEMAT PV RATE RECEIVED SLN SYD TBILLEQ TBILLPRICE"
            + " TBILLYIELD VDB XIRR XNPV YIELD YIELDDISC YIELDMAT");
    groups.put("Logic", "FALSE TRUE IFNA IFS");
    groups.put(
        "Type & error checks",
        "ERROR.TYPE ISBLANK ISERR ISERROR ISEVEN ISLOGICAL ISNA ISNONTEXT ISNUMBER ISODD ISREF"
            + " ISTEXT N NA TYPE");
    groups.put("Lookup", "ADDRESS AREAS CHOOSE COLUMNS DGET LOOKUP ROWS TRANSPOSE XLOOKUP XMATCH");
    groups.put("Collections", "COUNTA COUNTBLANK COUNTIFS");
    groups.put(
        "Database", "DAVERAGE DCOUNT DCOUNTA DMAX DMIN DPRODUCT DSTDEV DSTDEVP DSUM DVAR DVARP");
    groups.put("Matrices", "MDETERM MINVERSE MMULT");
    groups.put(
        "Engineering",
        "BESSELI BESSELJ BESSELK BESSELY BIN2DEC BIN2HEX BIN2OCT COMPLEX CONVERT DEC2BIN DEC2HEX"
            + " DEC2OCT DELTA ERF ERFC GESTEP HEX2BIN HEX2DEC HEX2OCT IMABS IMAGINARY IMARGUMENT"
            + " IMCONJUGATE IMCOS IMDIV IMEXP IMLN IMLOG10 IMLOG2 IMPOWER IMPRODUCT IMREAL IMSIN"
            + " IMSQRT IMSUB IMSUM OCT2BIN OCT2DEC OCT2HEX");
    var result = new HashMap<String, String>();
    groups.forEach(
        (category, names) -> {
          for (String name : names.split(" ")) result.put(name, category);
        });
    return Map.copyOf(result);
  }

  private ExcelFunctionCategories() {}
}
